name: npm tests
on: push
jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - mame: Get code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test


        